backend: compose
defaults:
  group: ${{ env.SUGAR_GROUP }}
  project-name: mhai

groups:
  dev:
    config-path:
      - containers/compose.dev.yaml
    services:
      default: mhai-web-deps
      available:
        - name: mhai-web-deps

  prod:
    config-path:
      - containers/compose.prod.yaml
    services:
      default: mhai-web-deps
      available:
        - name: mhai-web-deps
